# Generated by Django 5.2.11 on 2026-02-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='user_agent',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
