# Generated by Django 5.2.11 on 2026-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_session_ip_address_session_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
